name: Build and Deploy Storybook on Manual
on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup ğŸ¨
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 7

      - name: Cache dependencies ğŸ“¦
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: packages/shared-ui/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install ğŸš€
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        working-directory: packages/shared-ui
        run: |
          pnpm install --no-frozen-lockfile

      - name: Build ğŸ”§
        working-directory: packages/shared-ui
        run: |
          pnpm -r run build-storybook-docs

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: packages/shared-ui/docs-build
          target-folder: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
